  cF  Total Unread ForYou   Name                       [0;37m!  cJCurrent user profile[0;37m
  cF=================================================  [0;37m!  cJ--------------------[0;37m
  cH     42     20     cI10cH * cCPrivate                    [0;37m!  cKUser name: cLSuper User[0;37m
  cG-------------------------------------------------  [0;37m!  cKLines:     cL24[0;37m
                                                     !
---------------------------------------+-------------+-------------------------
                                       !
cMCaller     Nick  Type  When  Status    [0;37m!   Move with cursor keys, [1;37mQ[0;37muit, [1;37mA[0;37mbort
cM------     ----  ----  ----  ------    [0;37m!   Available colors: [30mX[31mX[32mX[33mX[34mX[35mX[36mX[37mX[1;30mX[1;31mX[1;32mX[1;33mX[1;34mX[1;35mX[1;36mX[1;37mX[0;37m
cYOff User   cWZ     cQnet   cU11:11 cSLogout    [0;37m!
cXBusy User  cVB     cPlocal cT12:34 cRActive    [0;37m!
                                       !
---------------------------------------+
                                       !
cxJcwoin group    scxOcwrt:  cynone  czalphabetic  [0;37m!
                                       !
  cCPrivate           cELocal post area    [0;37m!
  cDNetMail           cENetwork post area  [0;37m!
cEu cAMain Board        cELocal area         [0;37m!
  cBBBBS.English      cENetwork area       [0;37m!
                                       !
                                       !