
[1;31mExtended Chat Commands:[0;37m

[1;33m/S[0;37may message           Send a message to your current target.
[1;33m/M[0;37me message            Send a message as feeling.
[1;33m/MS[0;37mg target message    Send a message to a given target. You can use this
[0;37m                       command to send messages to other channels or users
[0;37m                       than your current target.
[1;33m/T[0;37marget newtarget      Change your current target to another channel, nick or
[0;37m                       node. You can combine multiple targets with [1;33m+[0;37m sign.
[1;33m/J[0;37moin channel          Join a channel.
[1;33m/R[0;37mesign channel        Resign from a non-obligatory channel.
[1;33m/REP[0;37mort                Show a list of all available channels.
[1;33m/L[0;37mist {class}          List all feelings (belonging to class).
[1;33m/W[0;37mho                   Show a list of all users who are logged on.
[1;33m/TI[0;37mme                  Show your time left.
[1;33m/LA[0;37mst                  Repeat last messages received.
[1;33m/NI[0;37mck newnick          Change your nick.
[1;33m/IGN[0;37more nicklist       Ignore messages coming from nicks.
[1;33m/%[0;37m command             Send IRC command.
[1;33m/WIN[0;37mdow command        Windows in groupchat: NEW|Kill|Listen|Size|Next|Prev|LOG
[1;33m/IRCJ[0;37moin               Join to Internet Relay Chat.
[1;33m/IRCQ[0;37muit               Quit from Internet Relay Chat.
[1;33m/Q[0;37muit                  Quit from groupchat.
[1;33m*feeling[0;37m {focus} {*"grade"} {<"extension"} {@color}
[0;37m                       Send a feeling. See [1;33m/L[0;37mist for available feelings.

[1;31mShortcuts:[0;37m >target = /MSg target, channel = /MSg channel, !text = /Say text

[0;37mPrefix IRC names with '[1;33m%[0;37m', for example "[1;33m/j %#chat[0;37m" and "[1;33m>%nick text[0;37m".
[0m
