[1;31mGlobal Commands:[0;37m

<[1;33mQ[0;37m> main menu             <[1;33mE[0;37m>nter a message          <[1;33mWHO[0;37m>'s on other nodes
<[1;33mR[0;37m>ead menu (or [1m[ENTER][0;37m)  <[1;33mJ[0;37m>oin/resign msg areas    <[1;33mCHAT[0;37m> menu
<[1;33mF[0;37m>ile menu               <[1;33mMD[0;37m> download messages     <[1;33m/?[0;37m> ext. chat menu
<[1;33mU[0;37m>tility menu (settings) <[1;33mMU[0;37m> upload replies        <[1;33mH[0;37m>elp about using BBBS
<[1;33mB[0;37m>ulletin menu           <[1;33mCOM[0;37m>ment message to SysOp <[1;33mNEWU[0;37m>ser help
<[1;33mG[0;37m>oodbye (logout)        <[1;33mTIM[0;37m>e left now            [1mcmnd -h[0;37m shows command help
[0m
