[1;1H[2J[1;31mMain Commands:[0;37m

<[1;33mS[0;37m>how list of users      <[1;33mBA[0;37m> time bank             <[1;33mVER[0;37m> show version info
<[1;33mSTAT[0;37m>istics about BBS    <[1;33mCAL[0;37m> view calendar        <[1;33mOP[0;37m>en a door
<[1;33mI[0;37m>nfo about user         <[1;33mBR[0;37m>owse nodelist              (online games)
<[1;33mA[0;37m>nswer questionnaire    <[1;33mJA[0;37m>rgon search            <[1;33mADDON[0;37m> commands
<[1;33mTEL[0;37m>net                  <[1;33mRL[0;37m>ogin                   <[1;33mFIN[0;37m>ger
<[1;33mFTP[0;37m>                     <[1;33mHUNT[0;37m>                     <[1;33mHACK[0;37m>
<[1;33mCALL[0;37m>back                <[1;33mURL[0;37m> download url         <[1;33mV[0;37m>ote booth
[0m
