
[1;31mTerminal type choices:[0;37m    <[1;33m?[0;37m> help

<[1;33mT[0;37m>ty             Teletype, no screen emulation
<[1;33mD[0;37m>ummyANSI       Veeeery slow, but should work on all toy-terminals too
<[1;33mA[0;37m>NSI X3.64      Real screen emulation with real scrolling of lines
<[1;33mV[0;37m>T320           Most advanced screen emulation
<[1;33mR[0;37m>IP             Screen emulation with graphics, but toy-scrolling
[0m
