
[1;31mUtility Commands:[0;37m    <[1;33m?[0;37m> help    <[1;33mQ[0;37m> main menu    <[1;33mR[0;37m>eadmenu    <[1;33mF[0;37m>iles

<[1;33mV[0;37m>iew current settings    <[1;33mP[0;37m> change your password  <[1;33mRES[0;37m> edit resume msg
<[1;33mLA[0;37m>nguage used in menus   <[1;33mX[0;37m> expert/novice menus   <[1;33mA[0;37m>ddress data
<[1;33mTE[0;37m>rminal emulation type
[0m
