<[1;35mFIND[0;37m> user or group      <[1;35mTLI[0;37m> time limit           <[1;35mSYS[0;37m>op level
<[1;35m+[0;37m> find next user        <[1;35mBA[0;37m> time in time bank     <[1;35mSTA[0;37m> change status
<[1;35m-[0;37m> find previous user    <[1;35mFACC[0;37m> file access         <[1;35mINV[0;37m>ite to conference
<[1;35mKILL[0;37m> this user          <[1;35mLIM[0;37m> change limits        <[1;35mUNINV[0;37m>ite from conference
<[1;35mAAS[0;37m>sign to account      <[1;35mAAD[0;37m>d money               <[1;35mAC[0;37m>hange flags
<[1;35mAV[0;37m>iew account           <[1;35mAM[0;37m>embers of account      <[1;35mWOTU[0;37m> WandOfTurnUndead
<[1;35mFUP[0;37m> files up            <[1;35mBUP[0;37m> bytes up             <[1;35mCALL[0;37m> times on
<[1;35mFD[0;37m> files down           <[1;35mBD[0;37m> bytes down
[0m
